### PR TITLE
added gzip to client and server side of gorest

### PR DESCRIPTION
**Pull request by mikeburkat**

### CODE REVIEW

**Comment by jsbejeau** [comment]
Seems good.
We could also add the compression type in Gzip function when we send a request.
+1

**Comment by mikeburkat** [comment]
you mean the compression level? or having different compression types like adding bzip2, or flat...

**Comment by jsbejeau** [comment]
yes...currently it is bestSpeed, but we could add option to change that with a variadic input, I guess, to allow empty/ default parameter

**Comment by jraby** [comment]
nice work!

IMO we should set it to defaultCompression, which is usually 6, which should be just fine for most cases.
IIRC anything above 6 is slow and doesn't yield much better compression.

**Comment by mikeburkat** [comment]
you are right the default is 6  in go also.
I could set it to that.

**Comment by mikeburkat** [comment]
@jraby @jsbejeau using compression level now, so 0 is none, and you can use the gzip constants otherwise, or any int.

**Comment by jsbejeau** [comment]
cool +1

**Pull request merged**
